language: python
python:
  - "3.8"
# command to install dependencies
install:
  - pip install -r app/requirements.txt
  - pip install codecov
# command to run tests
script:
  - pytest -s
after_success:
  - codecov
