language: python
python:
  - "3.8"
# command to install dependencies
services:
  - docker
before_install:
  - docker build -t carlad/sinatra .
install:
  - pip install -r app/requirements.txt
  - pip install codecov
# command to run tests
script:
  - pytest -s
after_success:
  - codecov


